"use client";

import "./globals.css";

import { AppBar, Toolbar, Typography, Link } from "@mui/material";

export const metadata = {
  title: "Material UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppBar>
          <Toolbar>
            <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
              <Link href="/" color="secondary" underline="hover">
                Home
              </Link>
            </Typography>
          </Toolbar>
        </AppBar>
        {children}
      </body>
    </html>
  );
}
